name: Build ASR Toolchain (mac)

on:
    workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build_bare_mac:
    name: baremetal for ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
    env: 
      CC: gcc-8
      CXX: g++-8

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Install Dependencies on macOS
      if: startsWith(matrix.os, 'macOS')
      run: |
          brew install zlib expat gawk gnu-sed
    - name: Configure
      run: |
        PREFIX=${HOME}/riscv
        ./configure --with-arch=rv32gc --enable-multilib --prefix=$PREFIX --with-cmodel=medany
        cd ./riscv-gcc/ && ./contrib/download_prerequisites
        cd -
    - name: Change toolchain name to asr
      run: |
        sed -i -e 's/make_tuple = riscv$(1)-unknown-$(2)/make_tuple = riscv-asr-$(2)/g' Makefile
    - name: Build Toolchain
      run: |
        export MAKE="make -j4"
        make
    - name: Archive Toolchain
      run: |
        PREFIX=${HOME}/riscv
        tar -jcf asr_riscv_gnu_toolchain_prebuilt_elf_${{ matrix.os }}.tar.bz2 -C $PREFIX .
    - name: Upload built toolchain artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: asr_riscv_gnu_toolchain_prebuilt_elf_${{ matrix.os }}
        # A file, directory or wildcard pattern that describes what to upload
        path: asr_riscv_gnu_toolchain_prebuilt_elf_${{ matrix.os }}.tar.bz2
